### PR TITLE
Parse arguments to git_version, and implement pre-/suffixes and (cargo-)fallback

### LINKED ISSUE #10: mechanism to build outside a git repository
It would be nice to have a macro that does something other than crash when run outside a git repository, since cargo builds outside git repositories (see droundy/fac#24).  I could see this either working through a separate macro (`git_describe_or_cargo_version!`?), or via a special flag to `git_describe`.  Any preference for which mechanism you'd like for a pull request, or what you'd like to call the non-crashing macro?

### PR DESCRIPTION
**Pull request by m-ou-se**
Examples:

```rust
const VERSION: &str = git_version!();
const VERSION: &str = git_version!(args = ["--dirty", "--abbrev=40"]);
const VERSION: &str = git_version!(fallback = "unknown");
const VERSION: &str = git_version!(prefix = "git:", cargo_prefix = "cargo:");
const VERSION: &str = git_version!(suffix = "-git", cargo_suffix = "");
```

Fixes #10

### CODE REVIEW

**Comment by droundy** [comment]
I really don't like the complexity of this interface, and think that giving folks reasonable behavior by default would be superior.

Do you think anyone actually have a goal for their code to fail to compile outside a git repository? If not, why not at least make a default fallback? And once it has a default, does anyone need to change it? Surely the users of this crate normally compile their code in a git repo, and aren't likely to care much what happens to weird people who don't (except not really wanting it to fail to compile).

And then you can ask if anyone would prefer to have a version of "unknown" rather than the cargo version with some way to distinguish it from the git version? It's hard for me to imagine.  But again, since few of us compile without git (cargo install being the major exception), why would we care much what the version looks like in that case?

In general, I think a non-crashing default behavior will satisfy everyone and require very little documentation.

**Comment by m-ou-se** [comment]
Well, the entire point of of the `git-version` crate is to give the git version. Silently ignoring errors and not giving the git version seems like an odd default behaviour. For our software here at Fusion we definitely do want it to fail if it can't get the git version, since we always want to know the exact software version running on drones.

Also, it's rather common for software to use a specific `git-` version prefix or suffix for git versions, and no prefix/suffix for the manually configured version (in this case from Cargo). I don't think one default like adding `-cargo` would fit everybody.

**Comment by m-ou-se** [comment]
A quick code search through public GitHub repositories shows that people have a lot of different preferences. Some fall back to Cargo's version (usually without prefix/suffix), some directly to the string "no-git-version" or even a hardcoded "0.1.0", some error out. People can't even agree on the suffix to use for when there are uncommitted changes in the repository, like `-dirty` or `-modified` or `-changed` etc.

**Comment by m-ou-se** [comment]
A completely different way to do it is to not use prefixes/suffixes, but std::fmt-like placeholders. It could then simply pick the first one in which all the placfeholders are known. Something like:

```rust
version_fmt!("{git}", "{cargo}-cargo"); // v1.2-gabcd-modified  or  1.2.3-cargo

version_fmt!("{cargo} (git: {git})", "{cargo}", "unknown"); // e.g. 1.2.3 (git: v1.2-gabcd)

version_fmt!("{cargo}", "unknown ({git})", "unknown");
```

Might be more ~~complicated~~ interesting to implement, though, as there is no compile-time `format!()` macro producing a string literal. But I guess a simple string replacement could also work.

**Comment by droundy** [comment]
I'm fine with this option.  I can copy a but more boilerplate.

**Comment by de-vri-es** [comment]
Implementation looks good. We need a solution and there seems to be consensus, so lets go with this.

**Pull request merged**
