### PR TITLE
This implements a simple version of the macro, which falls back to the cargo version if the repo is not in git.

### PR DESCRIPTION
**Pull request by droundy**
I did this a while back, and am just now realizing I apparently didn't submit a pull request?

### CODE REVIEW

**Comment by bodo-hugo-barwich** [comment]
As far as I understood from the code there exists already a Cargo Version fallback logic which is enabled through the `cargo_prefix` flag:
[fallback logic through `cargo_prefix` flag](https://github.com/fusion-engineering/rust-git-version/blob/4d8786e659919d5baa208a6ebc6a063b15b157a4/git-version-macro/src/lib.rs#L174-L180)
```
		Err(_) if cargo_fallback => {
			if let Ok(version) = std::env::var("CARGO_PKG_VERSION") {
				let prefix = args.cargo_prefix.iter();
				let suffix = args.cargo_suffix;
				Ok(quote!(
					concat!(#(#prefix,)* #version, #suffix)
				))
```
It is documented at:
[`git_version::git_version` documentation at docs.rs](https://docs.rs/git-version/latest/git_version/macro.git_version.html)
> `cargo_prefix`, `cargo_suffix`: If either is given, Cargo’s version (given by the CARGO_PKG_VERSION environment variable) will be used if git fails instead of giving an error. It will be prefixed/suffixed by the given strings.

**Comment by hoijui** [comment]
please see #22

**Comment by de-vri-es** [comment]
Thanks for the PR!

This is rather specific though. I'd see more in providing something more general that gives an `Option`, allowing users to implement their own fallback mechanism.

**Comment by de-vri-es** [comment]
This has already been implemented with the `cargo_prefix/suffix` arguments and the `fallback` argument. Thanks for the PR though!

**Pull request closed without merging**
