### PR TITLE
Add git_version_count as a way to get the number of commits since HEAD

### PR DESCRIPTION
**Pull request by svenstaro**
I found that this is sometimes quite helpful when you can't use a hash for your version such as in Android apps.

### CODE REVIEW

**Comment by hoijui** [comment]
I don't understand why "number of commits since HEAD" is interesting; in which cases would that not be `0`?

**Comment by hoijui** [comment]
please see #22

**Comment by de-vri-es** [comment]
Agreed, HEAD is always your last commit :o

**Comment by de-vri-es** [comment]
Note that git describe can already print commit since the last tag. This isn't the total number of commits, but it should be good enough for `git_version!()`.

Feel free to reply if I misunderstood the point. I can re-open the issue.

**Pull request closed without merging**
